security:
  basic:
    enabled: true

spring:
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fast-family-example?useUnicode=true&characterEncoding=utf8

fast:
  family:
    security:
      enabled: true
      jwt:
        authoritiesKey: "fast-family-auth-key"
        secret: "fast-family-token-secret";
        tokenValidityInseconds: 1800
        tokenValidityInSecondsForRememberMe: 2592000
      validate:
        code:
          repository: imMemory
          sms: true

logging:
  level:
    org.springframework.security: debug