spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fast-family-example?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
logging:
  level: debug


mapper:
  notEmpty: true

fast:
  family:
    swagger2:
      restapi:
        backPackage: "com.fast.family.example"
      apiinfo:
        title: "fast-family swagger构建api文档"
        description: "简单优雅的restful风格"
        version: "1.0"

