#fast:
#  family:
#    datasource:
#      master:
#        hikaricp:
#          username: root
#          password: root
#          url: jdbc:mysql://localhost:3306/master-db?useUnicode=true&characterEncoding=utf8
#          driverClassName: com.mysql.jdbc.Driver
#      slave_0:
#        hikaricp:
#          username: root
#          password: root
#          url: jdbc:mysql://localhost:3306/slave-db?useUnicode=true&characterEncoding=utf8
#          driverClassName: com.mysql.jdbc.Driver

fast:
  family:
    datasource:
      master:
        atomikos:
          uniqueResourceName: master-db
          xaProperties:
            user: root
            password: root
            url: jdbc:mysql://localhost:3306/master-db?useUnicode=true&characterEncoding=utf8
#            driverClassName: com.mysql.jdbc.Driver
      slave_0:
        atomikos:
          uniqueResourceName: slave-db
          xaProperties:
            user: root
            password: root
            url: jdbc:mysql://localhost:3306/slave-db?useUnicode=true&characterEncoding=utf8
#            driverClassName: com.mysql.jdbc.Driver